---
name: Version Bump

on:
  workflow_dispatch:
    inputs:
      client:
        description: "Client Project"
        required: true
        type: choice
        options:
          - Browser
          - CLI
          - Desktop
          - Web
          - All
      version_number:
        description: "New Version"
        required: true

  workflow_call:
    inputs:
      version_number:
        required: true
        type: string
      client:
        required: true
        type: string
    secrets:
      AZURE_PROD_KV_CREDENTIALS:
        required: true

defaults:
  run:
    shell: bash

jobs:
  bump_version:
    name: "Bump ${{ github.event.inputs.client }} Version"
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Branch
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2

      - name: Login to Azure - Prod Subscription
        uses: Azure/login@92a5484dfaf04ca78a94597f4f19fea633851fa2 # v1.4.7
        with:
         creds: ${{ secrets.AZURE_KV_CI_SERVICE_PRINCIPAL }}

      - name: Retrieve secrets
        id: retrieve-secrets
        uses: bitwarden/gh-actions/get-keyvault-secrets@f07c58ae6d120bcfbb01f695074aff45c41e7627
        with:
          keyvault: "bitwarden-ci"
          secrets: "github-gpg-private-key, github-gpg-private-key-passphrase"

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@72b6676b71ab476b77e676928516f6982eef7a41 # v5.3.0
        with:
          gpg_private_key: ${{ steps.retrieve-secrets.outputs.github-gpg-private-key }}
          passphrase: ${{ steps.retrieve-secrets.outputs.github-gpg-private-key-passphrase }}
          git_user_signingkey: true
          git_commit_gpgsign: true

      - name: Create Version Branch
        id: branch
        env:
          CLIENT_NAME: ${{ github.event.inputs.client }}
          VERSION: ${{ github.event.inputs.version_number }}
        run: |
          CLIENT=$(python -c "print('$CLIENT_NAME'.lower())")
          echo "client=$CLIENT" >> $GITHUB_OUTPUT

          git switch -c ${CLIENT}_version_bump_${VERSION}

      ########################
      # VERSION BUMP SECTION #
      ########################

      ### Browser
      - name: Bump Browser Version
        if: ${{ github.event.inputs.client == 'Browser' || github.event.inputs.client == 'All' }}
        env:
          VERSION: ${{ github.event.inputs.version_number }}
        run: npm version --workspace=@bitwarden/browser ${VERSION}

      - name: Bump Browser Version - Manifest
        if: ${{ github.event.inputs.client == 'Browser' || github.event.inputs.client == 'All' }}
        uses: bitwarden/gh-actions/version-bump@f07c58ae6d120bcfbb01f695074aff45c41e7627
        with:
          version: ${{ github.event.inputs.version_number }}
          file_path: "apps/browser/src/manifest.json"

      - name: Bump Browser Version - Manifest v3
        if: ${{ github.event.inputs.client == 'Browser' || github.event.inputs.client == 'All' }}
        uses: bitwarden/gh-actions/version-bump@f07c58ae6d120bcfbb01f695074aff45c41e7627
        with:
          version: ${{ github.event.inputs.version_number }}
          file_path: "apps/browser/src/manifest.v3.json"

      - name: Run Prettier after Browser Version Bump
        if: ${{ github.event.inputs.client == 'Browser' || github.event.inputs.client == 'All' }}
        run: |
          npm install -g prettier
          prettier --write apps/browser/src/manifest.json
          prettier --write apps/browser/src/manifest.v3.json

      ### CLI
      - name: Bump CLI Version
        if: ${{ github.event.inputs.client == 'CLI' || github.event.inputs.client == 'All' }}
        env:
          VERSION: ${{ github.event.inputs.version_number }}
        run: npm version --workspace=@bitwarden/cli ${VERSION}

      ### Desktop
      - name: Bump Desktop Version - Root
        if: ${{ github.event.inputs.client == 'Desktop' || github.event.inputs.client == 'All' }}
        env:
          VERSION: ${{ github.event.inputs.version_number }}
        run: npm version --workspace=@bitwarden/desktop ${VERSION}

      - name: Bump Desktop Version - App
        if: ${{ github.event.inputs.client == 'Desktop' || github.event.inputs.client == 'All' }}
        env:
          VERSION: ${{ github.event.inputs.version_number }}
        run: npm version ${VERSION}
        working-directory: "apps/desktop/src"

      ### Web
      - name: Bump Web Version
        if: ${{ github.event.inputs.client == 'Web' || github.event.inputs.client == 'All' }}
        env:
          VERSION: ${{ github.event.inputs.version_number }}
        run: npm version --workspace=@bitwarden/web-vault ${VERSION}

      ########################

      - name: Setup git
        run: |
          git config --local user.email "106330231+bitwarden-devops-bot@users.noreply.github.com"
          git config --local user.name "bitwarden-devops-bot"

      - name: Check if version changed
        id: version-changed
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "changes_to_commit=TRUE" >> $GITHUB_OUTPUT
          else
            echo "changes_to_commit=FALSE" >> $GITHUB_OUTPUT
            echo "No changes to commit!";
          fi

      - name: Commit files
        if: ${{ steps.version-changed.outputs.changes_to_commit == 'TRUE' }}
        env:
          CLIENT: ${{ steps.branch.outputs.client }}
          VERSION: ${{ github.event.inputs.version_number }}
        run: git commit -m "Bumped ${CLIENT} version to ${VERSION}" -a

      - name: Push changes
        if: ${{ steps.version-changed.outputs.changes_to_commit == 'TRUE' }}
        env:
          CLIENT: ${{ steps.branch.outputs.client }}
          VERSION: ${{ github.event.inputs.version_number }}
        run: git push -u origin ${CLIENT}_version_bump_${VERSION}

      - name: Create Bump Version PR
        if: ${{ steps.version-changed.outputs.changes_to_commit == 'TRUE' }}
        env:
          PR_BRANCH: "${{ steps.branch.outputs.client }}_version_bump_${{ github.event.inputs.version_number }}"
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          BASE_BRANCH: master
          TITLE: "Bump ${{ github.event.inputs.client }} version to ${{ github.event.inputs.version_number }}"
        run: |
          gh pr create --title "$TITLE" \
            --base "$BASE" \
            --head "$PR_BRANCH" \
            --label "version update" \
            --label "automated pr" \
            --body "
              ## Type of change
              - [ ] Bug fix
              - [ ] New feature development
              - [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
              - [ ] Build/deploy pipeline (DevOps)
              - [X] Other

              ## Objective
              Automated ${{ github.event.inputs.client }} version bump to ${{ github.event.inputs.version_number }}"

